---
# initialize empty array
vms: []

# setup retry variables
max_retries: 100
retry_interval: 10

# retirement tags for the service and vms
retirement_category: lifecycle
retirement_tag: retire_full

### privileged credentials needed for post provision tasks ###
manageiq_user: admin
# Run the following to generate your own vaulted password string and replace the contents of
# manageiq_password. You will need to include a the vault password in your credentials
# i.e. ansible-vault encrypt_string smartvm
manageiq_password: "{{ YOUR_ENCRYPTED_PASS }}"

# turn ssl verify off
manageiq_validate_certs: false

# enable extra debugging
verbose: false
provider: "99000000000001"
