---
# tasks file for ldomb.bigip
- name: Create a pool
  bigip_pool:
      lb_method: "ratio-member"
      name: "{{ poolname }}"
      password: "{{ bigip_password }}"
      server: "{{ hostname }}"
      server_port: "{{ bigip_port }}"
      slow_ramp_time: "120"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  delegate_to: localhost

- name: Create node1
  bigip_node:
      host: "{{ item.0 }}"
      name: "{{ item.1 }}"
      password: "{{ bigip_password }}"
      server: "{{ hostname }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  delegate_to: localhost
  with_together: 
    - "{{ private_ip_addr_list }}"
    - "{{ private_dns_name_list }}"

- name: Add nodes to pool
  bigip_pool_member:
      description: "webserver-1"
      host: "{{ item.0 }}"
      name: "{{ item.1 }}"
      password: "{{ bigip_password }}"
      server_port: "{{ bigip_port }}"
      pool: "{{ poolname }}"
      port: "80"
      server: "{{ hostname }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
  delegate_to: localhost
  with_together:
    - "{{ private_ip_addr_list }}"
    - "{{ private_dns_name_list }}"

- name: Create a VIP
  bigip_virtual_server:
      description: "summit-vip"
      destination: "10.0.1.44"
      password: "{{ bigip_password }}"
      server_port: "{{ bigip_port }}"
      name: "{{ vip }}"
      pool: "{{ poolname }}"
      port: "443"
      server: "{{ hostname }}"
      snat: "Automap"
      user: "{{ bigip_username }}"
      all_profiles:
          - "http"
          - "clientssl"
      validate_certs: "{{ validate_certs }}"
  delegate_to: localhost
