---
# http://docs.ansible.com/ansible/latest/ec2_module.html
aws_access_key: "{{ YOUR_ENCRYPTED_ACCESS_KEY }}"

aws_secret_key: "{{ YOUR_ENCRYPTED_SECRET_KEY }}"

key_name: ldombaws    # key pair to use on the instance
group_id: "sg-0a880ac762b7ecaf6"     # security group id (or list of ids) to use with the instance
instance_type: t2.medium   # instance type to use for the instance
image: ami-7a96b801       # ami ID to use for the instance
vpc_subnet_id:           # list the subnet ID(s) in which to launch the instance (VPC), it will randomly choose one
  - subnet-0f4aa489a149e0248
region: us-east-1         # The AWS region to use. Must be specified if ec2_url is not used.
instance_tags:
  environment: "{{ tag_0_environment | default('dev') }}" # environment tag
  owner: "{{ userid | default('cloudforms') }}" # environment tag

assign_public_ip: true    # when provisioning within vpc, assign a public IP address.
count: 2               # number of instances to launch
wait: true                # wait for the instance to reach its desired state before returning. Does not wait for SSH.
termination_protection: false # Enable or Disable the Termination Protection

# volume stuff
device_name: /dev/sda1    # name of the volume
volume_size: 16           # size of the volume
delete_on_termination: true # delete volume on termination

# custom variables
verbose: false

# user_data/cloud-init script
user_data: |
      #cloud-config
      runcmd:
      ## setup motd
      - echo Provisioned by Red Hat CloudForms > /etc/motd
